<?= render_errors($errors) ?>
<form method="post" action="<?= e($form_action) ?>">
    <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
    <div class="form-section"><div class="form-section-title">Profil dokter</div><div class="form-grid">
        <div class="form-field"><label class="form-label" for="kode_dokter">Kode dokter <span class="required">*</span></label><input class="form-control mono" type="text" id="kode_dokter" name="kode_dokter" value="<?= e($data['kode_dokter']) ?>" maxlength="16" placeholder="Kode unik dokter" required></div>
        <div class="form-field"><label class="form-label" for="nama_dokter">Nama dokter <span class="required">*</span></label><input class="form-control" type="text" id="nama_dokter" name="nama_dokter" value="<?= e($data['nama_dokter']) ?>" maxlength="120" placeholder="dr. Nama Lengkap" required></div>
        <div class="form-field"><label class="form-label" for="specialization_id">Spesialisasi <span class="required">*</span></label><select class="form-control" id="specialization_id" name="specialization_id" required><option value="">Pilih spesialisasi</option><?php foreach ($specializations as $specialization): ?><option value="<?= e($specialization['id']) ?>" <?= (string) $data['specialization_id'] === (string) $specialization['id'] ? 'selected' : '' ?>><?= e($specialization['nama']) ?></option><?php endforeach; ?></select></div>
        <div class="form-field"><label class="form-label" for="status">Status dokter <span class="required">*</span></label><select class="form-control" id="status" name="status" required><option value="Aktif" <?= $data['status'] === 'Aktif' ? 'selected' : '' ?>>Aktif</option><option value="Nonaktif" <?= $data['status'] === 'Nonaktif' ? 'selected' : '' ?>>Nonaktif</option></select></div>
    </div></div>
    <div class="form-section"><div class="form-section-title">Kontak</div><div class="form-grid"><div class="form-field"><label class="form-label" for="no_hp">No. HP <span class="required">*</span></label><input class="form-control" type="tel" id="no_hp" name="no_hp" value="<?= e($data['no_hp']) ?>" maxlength="20" required></div><div class="form-field full"><label class="form-label" for="alamat">Alamat <span class="required">*</span></label><textarea class="form-control" id="alamat" name="alamat" required><?= e($data['alamat']) ?></textarea></div></div></div>
    <div class="form-section"><div class="form-section-title">Jadwal praktik</div><div class="form-grid">
        <div class="form-field full"><label class="form-label" for="jadwal_hari">Hari praktik <span class="required">*</span></label><input class="form-control" type="text" id="jadwal_hari" name="jadwal_hari" value="<?= e($data['jadwal_hari']) ?>" maxlength="120" placeholder="Senin - Jumat" required><span class="form-help">Ditampilkan pada profil akun dokter dan menu navigasi.</span></div>
        <div class="form-field"><label class="form-label" for="jam_mulai">Jam mulai <span class="required">*</span></label><input class="form-control" type="time" id="jam_mulai" name="jam_mulai" value="<?= e(substr((string) $data['jam_mulai'], 0, 5)) ?>" required></div>
        <div class="form-field"><label class="form-label" for="jam_selesai">Jam selesai <span class="required">*</span></label><input class="form-control" type="time" id="jam_selesai" name="jam_selesai" value="<?= e(substr((string) $data['jam_selesai'], 0, 5)) ?>" required></div>
    </div></div>
    <div class="form-actions"><a class="button button-secondary" href="<?= e(base_url('dokter/index.php')) ?>">Batal</a><button class="button button-primary" type="submit"><?= icon('check') ?><span><?= e($submit_label) ?></span></button></div>
</form>
